version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local

#docker-compose -f docker-compose-pg-only.yml up -d
#docker exec -it postgresql-postgres-1 psql -U postgres postgres